alter table DICTIONARIES_CUSTOMER add constraint FK_DICTIONARIES_CUSTOMER_COUNTRY foreign key (COUNTRY_ID) references DICTIONARIES_DICTIONARY_VALUE(ID);
create index IDX_DICTIONARIES_CUSTOMER_COUNTRY on DICTIONARIES_CUSTOMER (COUNTRY_ID);
